[package]
name = "mercurio-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
mercurio-foundation = { path = "../mercurio-foundation", version = "0.86.0" }
