use std::collections::BTreeSet;
use std::fmt::Write;

use crate::kir::KirDocument;
use crate::model::{Graph, MetamodelFeatureRegistry};

pub fn generate_typed_facades(
    document: &KirDocument,
) -> Result<String, Box<dyn std::error::Error>> {
    let graph = Graph::from_document(document.clone())?;
    let registry = MetamodelFeatureRegistry::build(&graph);
    let mut classes = document
        .elements
        .iter()
        .filter(|element| element.kind == "Metaclass")
        .collect::<Vec<_>>();
    classes.sort_by(|left, right| left.id.cmp(&right.id));

    let mut output = String::from(
        "// @generated by mercurio-codegen; do not edit.\nuse crate::kir::KirElement;\n\n",
    );
    let mut names = BTreeSet::new();
    for class in classes {
        let kind = class
            .id
            .rsplit([':', '.', '/'])
            .find(|part| !part.is_empty())
            .unwrap_or(class.id.as_str());
        let base_name = format!("{}Facade", pascal_identifier(&class.id));
        let mut struct_name = base_name.clone();
        let mut suffix = 2;
        while !names.insert(struct_name.clone()) {
            struct_name = format!("{base_name}{suffix}");
            suffix += 1;
        }
        writeln!(
            output,
            "#[rustfmt::skip]\n#[derive(Debug, Clone, Copy)]\npub struct {struct_name}<'a> {{ element: &'a KirElement }}\n"
        )?;
        writeln!(output, "#[rustfmt::skip]\nimpl<'a> {struct_name}<'a> {{")?;
        writeln!(output, "    pub const KIND: &'static str = {kind:?};")?;
        writeln!(output)?;
        writeln!(
            output,
            "    pub fn try_from(element: &'a KirElement) -> Option<Self> {{"
        )?;
        writeln!(
            output,
            "        (element.kind == Self::KIND).then_some(Self {{ element }})"
        )?;
        writeln!(output, "    }}")?;
        writeln!(output)?;
        writeln!(
            output,
            "    pub fn element(&self) -> &'a KirElement {{ self.element }}"
        )?;

        let mut seen = BTreeSet::new();
        for feature in registry.all_features_for(&graph, &class.id) {
            let method = rust_identifier(&feature.kir_property);
            if !seen.insert(method.clone()) {
                continue;
            }
            let property = &feature.kir_property;
            let many = feature.multiplicity_upper.as_deref() == Some("*")
                || feature
                    .multiplicity_upper
                    .as_deref()
                    .and_then(|value| value.parse::<u64>().ok())
                    .is_some_and(|upper| upper > 1);
            let type_label = feature.type_label.as_deref().unwrap_or_default();
            writeln!(output)?;
            if many {
                writeln!(
                    output,
                    "    pub fn {method}(&self) -> impl Iterator<Item = &'a serde_json::Value> {{"
                )?;
                writeln!(output, "        self.element.properties.get({property:?})")?;
                writeln!(output, "            .and_then(serde_json::Value::as_array)")?;
                writeln!(output, "            .into_iter().flatten()")?;
                writeln!(output, "    }}")?;
            } else if type_label.contains("Boolean") {
                writeln!(
                    output,
                    "    pub fn {method}(&self) -> Option<bool> {{ self.element.properties.get({property:?})?.as_bool() }}"
                )?;
            } else if type_label.contains("Integer") {
                writeln!(
                    output,
                    "    pub fn {method}(&self) -> Option<i64> {{ self.element.properties.get({property:?})?.as_i64() }}"
                )?;
            } else if type_label.contains("Real") || type_label.contains("Number") {
                writeln!(
                    output,
                    "    pub fn {method}(&self) -> Option<f64> {{ self.element.properties.get({property:?})?.as_f64() }}"
                )?;
            } else {
                writeln!(
                    output,
                    "    pub fn {method}(&self) -> Option<&'a str> {{ self.element.properties.get({property:?})?.as_str() }}"
                )?;
            }
        }
        output.push_str("}\n\n");
    }
    while output.ends_with("\n\n") {
        output.pop();
    }
    Ok(output)
}

fn pascal_identifier(value: &str) -> String {
    value
        .split(|character: char| !character.is_alphanumeric())
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            chars
                .next()
                .map(|first| first.to_uppercase().collect::<String>() + chars.as_str())
                .unwrap_or_default()
        })
        .collect::<String>()
}

fn rust_identifier(value: &str) -> String {
    let mut output = String::new();
    for (index, character) in value.chars().enumerate() {
        if character.is_ascii_uppercase() && index > 0 {
            output.push('_');
        }
        if character.is_alphanumeric() || character == '_' {
            output.push(character.to_ascii_lowercase());
        } else {
            output.push('_');
        }
    }
    if matches!(
        output.as_str(),
        "as" | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
    ) {
        output.push('_');
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::kir::KirElement;
    use serde_json::json;
    use std::collections::BTreeMap;

    #[test]
    fn emits_typed_scalar_accessors_deterministically() {
        let document = KirDocument {
            metadata: BTreeMap::new(),
            elements: vec![
                KirElement {
                    id: "Demo::Widget".to_string(),
                    kind: "Metaclass".to_string(),
                    layer: 1,
                    properties: BTreeMap::new(),
                },
                KirElement {
                    id: "feature.widget.name".to_string(),
                    kind: "MetamodelFeature".to_string(),
                    layer: 1,
                    properties: BTreeMap::from([
                        ("owner".to_string(), json!("Demo::Widget")),
                        ("kir_property".to_string(), json!("declared_name")),
                        ("type_label".to_string(), json!("String")),
                    ]),
                },
            ],
        };
        let first = generate_typed_facades(&document).unwrap();
        let second = generate_typed_facades(&document).unwrap();
        assert_eq!(first, second);
        assert!(first.contains("pub struct DemoWidgetFacade"));
        assert!(first.contains("pub fn declared_name(&self) -> Option<&'a str>"));
    }
}
